name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.head_ref || github.run_id }}{% endraw %}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 10
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        pyv: ['3.8', '3.9', '3.10', '3.11']
        include:
        - {os: ubuntu-latest, pyv: 'pypy3.8'}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python {% raw %}${{ matrix.pyv }}{% endraw %}
      uses: actions/setup-python@v4
      with:
        python-version: {% raw %}${{ matrix.pyv }}{% endraw %}

    - name: Upgrade pip and nox
      run: |
        python -m pip install --upgrade pip nox
        pip --version
        nox --version

    - name: Lint code and check dependencies
      run: nox -s lint safety

    - name: Run tests
      run: nox -s tests-{% raw %}${{ matrix.nox_pyv || matrix.pyv }}{% endraw %} -- --cov-report=xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v3.1.4

    - name: Build package
      run: nox -s build
{% if cookiecutter.docs != "False" %}
    - name: Build docs
      run: nox -s docs
{% endif -%}
